# fly.toml app configuration file generated for server-delicate-glade-3069 on 2025-06-11T23:27:53+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-delicate-glade-3069'
primary_region = 'sin'

[build]

[env]
  PORT = 3000
  URL = 'https://server-icy-cloud-6038.fly.dev/'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
